#!/usr/bin/python3
import sys
"""
a function that writes a string to a text file (UTF8)
and returns the number of characters written
"""


def main():
    list_num = []
    filepath = sys.argv[1]
    with open(filepath, "r", encoding="UTF_8") as fp:
        """ open the file with the command open (argv[1])"""
        for line in fp:
            num = int(line)
            """ convert string to number each line contain a number"""
            list_num = factors(num)
            print("{:d}={:d}*{:d}".format(num, list_num[0], list_num[1]))
            list_num.clear()


def factors(n):
    "function that return a list of factors"
    i = 2
    lst = []
    while(True):
        if ((n % i) == 0):
            lst.append(n // i)
            lst.append(i)
            return lst
        i += 1
if __name__ == '__main__':
    main()
